services:
  next-app:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - database
    env_file:
      - .env.development
  database:
    image: "postgres:16-alpine3.22"
    # environment:
    #   POSTGRES_PASSWORD: "password"
    env_file:
      - .env.development
    ports:
      - "5001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_postgres -d local_postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
